// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD012IBeaoEVJY9iQzGXxcpLmcOahrI6I4',
    appId: '1:88431901405:web:0543b1f3d00a67682a3934',
    messagingSenderId: '88431901405',
    projectId: 'iot-project-8a40e',
    authDomain: 'iot-project-8a40e.firebaseapp.com',
    storageBucket: 'iot-project-8a40e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5nEkTDDoHQnxU-461kKc5mYq0AfFq03M',
    appId: '1:88431901405:android:5c92864ba3d401e22a3934',
    messagingSenderId: '88431901405',
    projectId: 'iot-project-8a40e',
    databaseURL: 'https://iot-project-8a40e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-8a40e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKGx-_v6OEyxkRYZW-t3DZR0a3cSh4Qc0',
    appId: '1:88431901405:ios:62659631c5de28c52a3934',
    messagingSenderId: '88431901405',
    projectId: 'iot-project-8a40e',
    databaseURL: 'https://iot-project-8a40e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-project-8a40e.appspot.com',
    iosBundleId: 'com.example.iotProject',
  );

}